# -*- coding: utf-8 -*-
"""Copy of Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NIvSQk1ekPx8917_mHvlP6LayIcabH7f
"""

from google.colab import drive
drive.mount("/content/drive")

from sklearn.linear_model import LinearRegression

import numpy as np
import pandas as pd

# Custom Dataset for temperature and humidity readings
df = pd.read_csv("/content/drive/MyDrive/SmartFan/smart.csv")
print(df)

X = df[["temperature", "humidity"]]
Y = df["fan_speed"]

print(X.shape)
print(Y.shape)

#Training Phase
model = LinearRegression()
model.fit(X,Y)

# Parameters
model.coef_

model.intercept_